### ISSUE TITLE
Entrega de atividade 28/02/2024.

### ISSUE THREAD

**Issue by B0nam** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-A#10]
Link para a atividade: https://github.com/B0nam/pokeapi-desafio-profissional

**Comment by sumioshi** [comment]
https://github.com/sumioshi/desafioprofissional_buscapokemon

**Comment by willyantomaz** [comment]
https://github.com/willyantomaz/pokemon

**Comment by vini2luiz** [comment]
https://github.com/vini2luiz/desafio-profissional-1

**Comment by Joaopedrohb** [comment]
https://github.com/Joaopedrohb/DesafioProfissional5/blob/main/atividade-assincrona-151.js

**Comment by LorenzoBerg9** [comment]
https://github.com/LorenzoBerg9/28-01

**Comment by jeanunicesumar** [comment]
https://github.com/jeanunicesumar/2024-desafio-profissional-v-ESOFT5S-A/blob/main/151-pokemon/index.js

**Comment by cassiab13** [comment]
https://github.com/cassiab13/desafio/tree/main/Atividade_28022024
