### ISSUE TITLE
Avaliação - Sagas do Universo Marvel

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-A#14]
**Avaliação - Sagas do Universo Marvel**

O Universo Marvel, repleto de super-heróis, vilões e histórias épicas, tem sido uma fonte inesgotável de entretenimento e inspiração. Com a Marvel API, você tem acesso a uma riqueza de informações sobre este universo, desde personagens até as sagas que definem eras.

**Objetivo da Atividade**

Nesta atividade, você irá desenvolver uma API própria que servirá como um intermediário entre a Marvel API e o usuário final. Sua API irá focar em uma saga específica do Universo Marvel, permitindo aos usuários explorar os personagens envolvidos, os quadrinhos que compõem a saga, e mais. Você irá modelar esta informação através de entidades em seu sistema, sobre as quais você implementará operações CRUD (Create, Read, Update, Delete).

As primeiras rotas de sua API serão para buscar os dados da API da Marvel e salvar em seu banco de dados. Suas outras rotas serão para consulta e manipulação em seu próprio banco de dados.
Descrição da Atividade

**1. Registro na Marvel API:** Obtenha sua chave de API registrando-se no Marvel Developer Portal. Esta chave permitirá que sua API faça requisições para buscar dados necessários.

**2. Escolha de uma Saga:** Selecione uma saga do Universo Marvel para ser o foco da sua API. Esta escolha determinará os dados que você irá buscar e disponibilizar através da sua API.

**3. Modelagem das Entidades:**
**Personagens:** Crie uma entidade Personagem para mapear os dados dos personagens que aparecem na saga escolhida. Inclua atributos como nome, descrição, e URL da imagem.

**Quadrinhos (Comics):** Desenvolva uma entidade Comic que armazena informações sobre os quadrinhos que fazem parte da saga, como título, descrição, data de publicação, e capa.

**Criadores:** Crie uma entidade Criador que represente os criadores dos quadrinhos (roteiristas, desenhistas, etc.), incluindo nome, função, e quais quadrinhos contribuíram.

**4. Implementação do CRUD:** Para cada uma das entidades (Personagem, Comic, Criador), implemente operações CRUD que permitam criar, ler, atualizar e deletar registros no seu sistema.

**5. Rotas Auxiliares:** Deverão ser criadas pelo menos 5 rotas auxiliares para complementar a funcionalidade de sua aplicação. O que cada rota irá fazer fica a seu critério.
Exemplos: Rota para listar somente os roteiristas, uma rota para buscar todas as personagens do sexo feminino de determinada sagas, uma rota para contar o total de revistas de derminada saga, e assim por diante.

**6. Desenvolvimento de Testes:**
**Testes Automatizados:** Escreva testes unitários e de integração para garantir o correto funcionamento das operações CRUD e da lógica de negócios da sua API.
**Testes End-to-End (E2E):** Implemente testes E2E para simular o fluxo completo de uso da sua API, desde a requisição inicial até a resposta final.
**Teste de Carga:** Realize um teste de carga para avaliar a performance e a estabilidade da sua API sob condições de uso elevado.

**Entregáveis**
**Código Fonte da API:** Inclua todo o código desenvolvido para a API, organizado e documentado.
**Documentação das Rotas:** Forneça uma documentação clara das rotas disponíveis na sua API, incluindo os métodos HTTP suportados e os formatos de requisição/resposta.
**Relatórios de Testes:** Apresente os resultados dos testes automatizados, E2E, e de carga, incluindo qualquer ferramenta ou abordagem utilizada para realizá-los.
A ferramenta Jest gera um relatório de cobertura de testes, sendo assim, a meta é alcançar 90% de cobertura de testes na aplicação.

**Critérios de Avaliação**
Completeness das operações CRUD para cada entidade.
Qualidade e cobertura dos testes implementados.
Performance e robustez da API, especialmente sob carga.
Clareza da documentação e facilidade de uso da API.

**Notas Finais**
Esta atividade não apenas aprofunda seu entendimento do Universo Marvel, mas também desenvolve habilidades cruciais em design de API, modelagem de dados, e testes de software. Boa sorte, e que a força dos super-heróis esteja com você!

Aqui estão algumas das sagas mais icônicas e populares da Marvel que você pode utilizar:

**1. Guerra Civil (Civil War) -** Uma disputa ideológica entre o Capitão América e o Homem de Ferro sobre o registro de super-heróis, levando a uma batalha épica entre heróis da Marvel.

**2. Guerras Secretas (Secret Wars) -** Heróis e vilões são transportados para um planeta distante chamado Battleworld pelo ser todo-poderoso conhecido como Beyonder para lutar em uma guerra sem precedentes.

**3. Era de Ultron (Age of Ultron) -** Ultron, uma inteligência artificial, decide erradicar a humanidade e os heróis da Marvel devem encontrar uma maneira de detê-lo.

**4. Dinastia M (House of M) -** Após um colapso nervoso, a Feiticeira Escarlate altera a realidade para criar um mundo onde os mutantes são a classe dominante, com consequências devastadoras.

**5. Infinito (Infinity) -** Thanos busca as Joias do Infinito para impor sua vontade sobre a realidade, levando os heróis da Terra e do espaço a se unirem para detê-lo.

**6. Aniquilação (Annihilation) -** Uma saga cósmica onde Annihilus, do Universo Negativo, lança uma invasão ao universo principal, ameaçando toda a vida existente.

**7. Planeta Hulk -** O Hulk é exilado no espaço por um grupo de heróis da Terra e acaba em um planeta onde se torna um gladiador e eventualmente um rei.

**8. A Queda de Mutantes (The Fall of the Mutants) -** Uma série de eventos que afetam drasticamente os X-Men e outros mutantes, levando a mudanças significativas para muitos personagens.

**9. Guerra dos Reinos (War of the Realms) -** Malekith, o Maldito, lidera um exército de criaturas míticas em uma invasão aos Nove Reinos, incluindo a Terra.

**10. X-Men: Fênix Negra (The Dark Phoenix Saga) -** Jean Grey se torna possuída pela força da Fênix, transformando-a na Fênix Negra, uma entidade de poder imenso e destrutivo.
Estas sagas oferecem uma variedade de temas e aventuras, desde conflitos internos entre heróis até ameaças cósmicas, ideais para explorar diferentes aspectos do Universo Marvel.

**11. King in Black -**  é uma saga épica da Marvel Comics que serve como culminação de várias histórias escritas por Donny Cates, especialmente aquelas envolvendo o personagem Venom. Lançada entre 2020 e 2021, a história centraliza-se em torno da chegada de Knull, o deus dos simbiontes, à Terra. Knull é uma entidade cósmica antiga que criou os simbiontes (a raça alienígena à qual pertence o Venom) e deseja trazer escuridão e destruição ao universo, eliminando toda a luz e vida que encontra pelo caminho.

**Comment by natanaelbalbo** [comment]
https://github.com/natanaelbalbo/MARVEL-API-SAGA-IRON-AGE

**Comment by natanaelbalbo** [comment]
alunos: Natanael Figueredo Balbo RA: 22014185-2, Arthur vinicius de oliveira semensati RA: 231051492, SAGA: Iron Age 
https://github.com/natanaelbalbo/MARVEL-API-SAGA-IRON-AGE
