### ISSUE TITLE
Entrega Avaliação - Sagas do Universo Marvel

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-A#16]
Faça a entrega nos comentários dessa issue, por favor indique os nomes e RAs presentes na dupla e o link para o repositório no github.
Faça somente uma entrega por dupla.

Data limite: 04/05/2024

**Comment by natanaelbalbo** [comment]
alunos: Natanael Figueredo Balbo RA: 22014185-2, Arthur vinicius de oliveira semensati RA: 231051492, SAGA: Iron Age
https://github.com/natanaelbalbo/MARVEL-API-SAGA-IRON-AGE

**Comment by sumioshi** [comment]
🎓 **Aluno 1:** Rodrigo Shodi Sumioshi - **RA:** 22014191-2
🎓 **Aluno 2:** Vinicius Luiz Santa Rosa - **RA:** 24042121-2

https://github.com/sumioshi/spider-verso-desafio-profissional

**Comment by EnzoLavieri** [comment]
Aluno 1: Enzo D Andrey Lavieri Yarid - RA:22308404-2
Aluno 2: Daniel Cardoso Martins - RA:22262100-2

https://github.com/EnzoLavieri/provaDesafioProfissional

**Comment by Yvesmorello** [comment]
Aluno 1: Yves Morello Pereira RA: 22014055-2
Aluno 2: Pedro Antônio Paiva Boeing RA: 22014162-2

https://github.com/Yvesmorello/PROVA-BUSSOLA

**Comment by AlineMisugui** [comment]
Aluno 1: Aline Ayumi Misugui  RA: 22110034-2
Aluno 2: Emerson Tanno Brizotto  RA: 22048194-2 

https://github.com/AlineMisugui/marvel-api

**Comment by yDezembro** [comment]
Aluno 1: Gabriel dos Santos Dezembro RA:22201764-2
 https://github.com/yDezembro/DesafioProfissional

**Comment by pedroHenriqueLomba** [comment]
João Antônio Garcia Rolo - R.A: 220143992
Pedro Lomba - R.A: 22162698-2
https://github.com/pedroHenriqueLomba/desafio-marvel

**Comment by gustavoarnoni** [comment]
Aluno 1: Gustavo dos Santos Arnoni - RA: 22014037-2
Aluno 2: Vitor Kenji Kumasaka Watanabe - RA: 22143204-2
https://github.com/gustavoarnoni/api-marvel

**Comment by Herick-Emanuel** [comment]
Aluno 1: João Gabriel Antunes - RA :22074884-2
Aluno 2: João Paulo de Andrade Gonçalves - RA: 22012646-2

https://github.com/Herick-Emanuel/marvel

**Comment by LorenzoMBegnozzi** [comment]
Vinicius Monteiro de Araujo Vilela- RA: 22276395-2
Lorenzo Marzola Begnozzi - RA: 23067179-2

https://github.com/LorenzoMBegnozzi/Api-Marvel

**Comment by gabriel-guerra** [comment]
Gabriel Sestito Guerra RA: 23025044-2
Lucas Niguti Dos Santos RA: 22019975-2

https://github.com/gabriel-guerra/desafio-v-prova-1

**Comment by rvbs1337** [comment]
Amanda Kaori Odo RA: 22023713-2
Rubens Pereira Junior RA: 22023714-2

https://github.com/rvbs1337/prova-dp5s-1bim

**Comment by mateusfb1103** [comment]
Mateus Felipe Brunetti dos Santos RA: 22012698-2      
Vitor Galetti Martins RA: 22019959-2
https://github.com/mateusfb1103/prova_DesafioProfissional

**Comment by AndreJacobx** [comment]
Aluno 1: André Luis Jacob Roman RA: 22014551-2
Aluno 2: Gustavo Falavinha RA: 22015750-2

https://github.com/AndreJacobx/provasagamarvel

**Comment by TalDoKenji** [comment]
aluno: Vinicius Kenji Uda RA: 22259133-2
https://github.com/TalDoKenji/prova-DesafioProfissional

**Comment by Berkhz** [comment]
## Avaliação Entregue

Aluno: **Kauan Henrique Bertalha**  
RA: *22262074-2*

[Repositório do Projeto](https://github.com/Berkhz/king-in-black-marvel)

**Comment by EfigenioGuerra** [comment]
Efigênio Guerra Neto RA: 22228289-2
Matheus Toscano Rossini RA: 22212262-2

https://github.com/EfigenioGuerra/marvelAPI

**Comment by jeanunicesumar** [comment]
Nome: Jean Aparecido de Almeida Soares RA.: 22254287-2
Nome: Cassia Yumi Iwamoto Basso RA.: 22265008-2

Repositório: https://github.com/cassiab13/guerras_secretas

**Comment by SenhorAfonso** [comment]
Nome: Rhayssa Justino Andretto. RA.: 21163127-2.
Nome: Pedro Afonso C. Sena. RA.: 22013787-2.

Repositório: https://github.com/SenhorAfonso/marvel-api

**Comment by willyantomaz** [comment]
Nome: Willyan Santos Tomaz e Silva RA: 22014128-2
Nome: Gabriel Alexandre Marassi RA: 22302091-2

Repositório: https://github.com/willyantomaz/prova_ds_profissional

**Comment by WillianKakihata** [comment]
Nome: Willian Hideaki Kakihata RA:22015763-2
Nome: Renan Tonon de Oliveira RA:  22188153-2

Repositório: https://github.com/WillianKakihata/marvel-guerra-dos-reinos-api

**Comment by kaikdorvalo** [comment]
Kaik Dorvalo dos Santos     RA: 22093919-2
Matheus Felinto da Silva     RA: 22012684-2

Repositório: https://github.com/Velinu/age-of-ultron-back-end-

**Comment by RicardooFilho** [comment]
Ricardo Francisco da Silva Filho - RA: 22019957-2
João Pedro Hieda Bortolotto - RA: 22231114-2

Repositório: https://github.com/RicardooFilho/marvel-api

**Comment by LuisZanin** [comment]
LUIS EDUARDO ZANIN DE TOLEDO RA: 22199411-2
RENATA HELOISA SARAIVA CASONI RA: 22272753-2

Repo: https://github.com/LuisZanin/Node

**Comment by RafaelFuzii** [comment]
Rafael Yuzo Fuzii RA: 22257557-2
Henrique Manganoti Pereira RA: 22012634-2

repo: https://github.com/RafaelFuzii/Marvel
