### ISSUE TITLE
Entrega Trabalho - To do List

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-A#17]
Faça a entrega nos comentários dessa issue, por favor indique os nomes e RAs presentes na dupla e o link para o repositório no github.
Faça somente uma entrega por dupla.

Data Limite 29/04/2024

**Comment by natanaelbalbo** [comment]
Natanael Figueredo Balbo RA:22014185-2, Arthur vinicius de oliveira Semensati RA: 23105149-2

https://github.com/natanaelbalbo/gerenciador-de-tarefas-api-desafio-profissional

**Comment by jeanunicesumar** [comment]
Nome: Jean Aparecido de Almeida Soares. R.A.: 22254287-2
Link: https://github.com/jeanunicesumar/2024-desafio-profissional-v-ESOFT5S-A/tree/main/api/tasks

**Comment by RicardooFilho** [comment]
Ricardo Francisco da Silva Filho - R.A 22019957-2
João Pedro Hieda Bortolotto - R.A 22231114-2
https://github.com/RicardooFilho/prova-pratica-bussola

**Comment by cassiab13** [comment]
Cassia Yumi Iwamoto Basso RA: 22265008-2
https://github.com/cassiab13/desafio/tree/main/Atividade_Bussola

**Comment by joaoagr1** [comment]
João Antônio Garcia Rolo - R.A: 220143992
Pedro Lomba - R.A: 22162698-2
https://github.com/joaoagr1/task-manager-api-node-mongodb-express

**Comment by rvbs1337** [comment]
Rubens Pereira Junior R.A: 22023714-2
Amanda Kaori Odo R.A: 22023713-2
https://github.com/rvbs1337/dp5s-2024

**Comment by kaikdorvalo** [comment]
Kaik Dorvalo dos Santos  RA: 22093919-2

https://github.com/kaikdorvalo/gerenciador-tarefas

**Comment by gabriel-guerra** [comment]
Gabriel Sestito Guerra RA: 23025044-2
https://github.com/gabriel-guerra/desafio-5-gerenciador-tarefas

**Comment by TalDoKenji** [comment]
Vinicius Kenji Uda - 22259133-2
https://github.com/TalDoKenji/desafioprofissional20-03

**Comment by EmersonTanno** [comment]
Emerson Tanno Brizotto - RA: 22048194-2
https://github.com/EmersonTanno/dp_5_trabalho_task_list

**Comment by Velinu** [comment]
Matheus Felinto da Silva - RA: 22012684-2
https://github.com/Velinu/task-manager

**Comment by LucasDNiguti** [comment]
Lucas Niguti Dos Santos RA: 22019975-2

Link: https://github.com/LucasDNiguti/DesafioProf5

**Comment by dcarm3** [comment]
Daniel Cardoso Martins RA: 22262100-2
https://github.com/dcarm3/to-do-API

**Comment by SenhorAfonso** [comment]
Pedro Afonso Cordeiro Sena. RA: 22013787-2
https://github.com/SenhorAfonso/task-manager

**Comment by RafaelFuzii** [comment]
Rafael Yuzo Fuzii  RA: 22257557-2
[https://github.com/RafaelFuzii/ListaTarefa](url)

**Comment by RafaelFuzii** [comment]
Rafael Yuzo Fuzii RA: 22257557-2
https://github.com/RafaelFuzii/ListaTarefa

**Comment by LorenzoMBegnozzi** [comment]
Lorenzo Marzola Begnozzi RA: 23067179-2
https://github.com/LorenzoBerg9/Gerenciador-de-tarefas

**Comment by Yvesmorello** [comment]
Yves Morello Pereira RA: 22014055-2
Pedro Antônio Paiva Boeing RA: 22014162-2

https://github.com/Yvesmorello/atividade-tasks

**Comment by ashura-senpai** [comment]
Henrique Manganoti Pereira RA: 22012634-2
https://github.com/ashura-senpai/api-gerenciador-de-tarefas

**Comment by willyantomaz** [comment]
Willyan Santos Tomaz e Silva ra:220141282

André Luis Jacob Roman
ra: 220145512

https://github.com/willyantomaz/Atividade_node/tree/main/task_node

**Comment by Herick-Emanuel** [comment]
Nome: João Gabriel Antunes RA:22074884-2

https://github.com/Herick-Emanuel/Trabalho-Desafio

**Comment by joaoarteagle** [comment]
Nome: João Paulo de Andrade Gonçalves 
RA: 22012646-2

[Repositório do Git](https://github.com/joaoarteagle/API-NodeJs)

**Comment by ViniciusMVilela** [comment]
Vinicius Monteiro de Araujo Vilela
22276395-2
https://github.com/ViniciusMVilela/ToDoList.git

**Comment by Berkhz** [comment]
*Nome:* `Kauan Henrique Bertalha`
*RA:* `22262074-2`

> Link do repositório contendo a atividade proposta.
[Clique Aqui!](https://github.com/Berkhz/learnNode/tree/main/listaTarefas)

**Comment by Berkhz** [comment]
*Nome:* `Kauan Henrique Bertalha`
*RA:* `22262074-2`

> Link do repositório contendo a atividade proposta.
[Clique Aqui!](https://github.com/Berkhz/learnNode/tree/main/listaTarefas)

**Comment by EfigenioGuerra** [comment]
Nome: Efigênio Guerra Neto
RA: 22228289-2

Repositório: https://github.com/EfigenioGuerra/desafioprofissional-task-api

**Comment by EnzoLavieri** [comment]
Nome: Enzo D Andrey Lavieri Yarid
RA: 22308404-2
Link do repositório da atividade: https://github.com/EnzoLavieri/aplicativoDeGerenciamentoDeTarefas

**Comment by LuisZanin** [comment]
Nome: Luis Eduardo Zanin de Toledo 
RA: 22199411-2
Nome: RENATA HELOISA SARAIVA CASONI
RA: 22272753-2
Repositório: https://github.com/LuisZanin/Node-5S-A

**Comment by WillianKakihata** [comment]
Nome: Willian Hideaki Kakihata
RA: 22015763-2
Repositório: https://github.com/WillianKakihata/gerenciador-de-tarefas

**Comment by arthvin** [comment]
Natanael Figueredo Balbo RA:22014185-2
Arthur vinicius de oliveira Semensati RA: 23105149-2
https://github.com/natanaelbalbo/gerenciador-de-tarefas-api-desafio-profissional

**Comment by MatheusTosRos** [comment]
Matheus Toscano Rossini 
RA: 22212262-2
https://github.com/MatheusTosRos/projeto_nodejs

**Comment by AlineMisugui** [comment]
Aline Ayumi Misugui
RA: 22110034-2
https://github.com/AlineMisugui/to-do-list-api
