### ISSUE TITLE
Atividade - 29/05/2024

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-A#19]
1 - Criar um novo CRUD de produtos: 
  - nome
  - valor
  - quantidade

2 - Criar um middleware que altera o valor do atributo **valor** multiplicando ele por 1.25

3 - Adicionar Exceptions em todos os métodos da controller e pelo menos uma Exception deve ser personalizada

4 - Adicionar os Validations pipes em todos os DTO's

nest g resource produtos

**Comment by natanaelbalbo** [comment]
Natanael Figueredo Balbo RA: 22014185-2
https://github.com/natanaelbalbo/nestJsAtividade.git

**Comment by cassiab13** [comment]
Cassia Yumi Iwamoto Basso RA 22265008-2
https://github.com/cassiab13/desafio/tree/main/books-nest

**Comment by pedroHenriqueLomba** [comment]
Pedro Henrique Lomba RA 22162698-2
https://github.com/pedroHenriqueLomba/nest-desafio-profissional

**Comment by EnzoLavieri** [comment]
Enzo D Andrey Lavieri Yarid. RA:22308404-2
https://github.com/EnzoLavieri/atividade-nest/tree/master/src/products

**Comment by ashura-senpai** [comment]
Henrique Manganoti Pereira RA: 22012634-2
https://github.com/ashura-senpai/books-nest-bussola

**Comment by Yvesmorello** [comment]
Yves Morello Pereira    RA: 22014055-2
https://github.com/Yvesmorello/atividade-2905

**Comment by RenataCasoni** [comment]
Renata Heloisa Saraiva Casoni R.A.: 22272753-2
https://github.com/RenataCasoni/Desafio-Profissional-5SA

**Comment by kaikdorvalo** [comment]
Kaik Dorvalo dos Santos   RA: 220939192
https://github.com/kaikdorvalo/books-nest

**Comment by MatheusTosRos** [comment]
Matheus Toscano Rossini RA: 22212262-2
https://github.com/MatheusTosRos/atividade-nest

**Comment by gabriel-guerra** [comment]
Gabriel Sestito Guerra RA: 23025044-2
https://github.com/gabriel-guerra/atividade-29-05
