### ISSUE TITLE
Entrega da avaliação 2 bimestre

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-A#21]
Entregue o link do repositório da sua avaliação. Só é necessário uma entrega por grupo.

Na resposta junto ao link informe o **nome** e **ra** dos integrantes do time.
Nomes de integrante faltando não serão considerados então informe tudo corretamente. 

Deixe o repositório público ou envie o invite para seu repositório (caso envie o convite deixe informado na reposta que o convite foi enviado)

**Comment by Yvesmorello** [comment]
Alunos: 

Yves Morello Pereira: 22014055-2
Pedro Antônio Paiva Boeing: 22014162-2
Gustavo Arnoni: 22014037-2
Vitor Kenji: 22143204-2

REPOSITÓRIO GIT:

https://github.com/Yvesmorello/API-DeD-Cadastro-User-JWT-NestJS-

**Comment by AlineMisugui** [comment]
Aline Ayumi Misugui: 22110034-2
Emerson Tanno Brizotto: 22048194-2
Kaik Dorvalo dos Santos: 22093919-2
Matheus Felinto da Silva: 22012684-2

https://github.com/AlineMisugui/dnd-api

**Comment by rvbs1337** [comment]
Amanda Kaori Odo 22023713-2
Rubens Pereira Junior 22023714-2

https://github.com/amamaxs2/dp-rpg

**Comment by pedroHenriqueLomba** [comment]
Pedro Henrique Lomba - Ra 22162698-2
Renata Heloisa Saraiva Casoni - Ra 22272753-2
Luis Eduardo Zanin de Toledo - Ra 22199411-2
João Antônio Garcia Rolo - Ra 22014399-2

Doc:
https://documenter.getpostman.com/view/28162406/2sA3XWdyhJ
App:
https://github.com/pedroHenriqueLomba/api-dd

**Comment by SenhorAfonso** [comment]
[Rotas](https://github.com/user-attachments/files/15948064/rpg.postman_collection.json)

https://github.com/SenhorAfonso/rpg-manager.git

Gustavo Falavinha: 22015750-2
Gabriel Dezembro: 22201764-2
João Gabriel Antunes: 22074884-2
Pedro Afonso C. Sena: 22013787-2

**Comment by rhayssaandretto** [comment]
- Cassia Yumi Iwamoto Basso R.A.: 22265008-2
- Jean Aparecido de Almeida Soares R.A.: 22254287-2
- Rhayssa Justino Andretto R.A.: 21163127-2
- Vinicius Kenji Uda R.A.: 22259133-2

[api-D&D.postman_collection.json](https://github.com/user-attachments/files/15948106/api-D.D.postman_collection.json)
[Repositório API](https://github.com/jeanunicesumar/API-dungeons-and-dragons)

**Comment by natanaelbalbo** [comment]
Natanael Figueredo Balbo RA: 22014185-2
Rodrigo Shodi Sumioshi RA: 22014191-2

https://github.com/natanaelbalbo/rpg-api-nestJs.git

**Comment by RafaelFuzii** [comment]
Rafael Yuzo Fuzii - 22257557-2
Henrique Manganoti Pereira - 22012634-2
Enzo D'Andrey Lavieri Yarid - 22308404-2
Daniel Cardoso Martins - 22262100-2

https://github.com/RafaelFuzii/Desafio_Profissional

Requisições:
[Desafio_Profissional.json](https://github.com/user-attachments/files/15948507/Desafio_Profissional.json)

**Comment by arthvin** [comment]
Arthur Vinicius - 231051492
Vinicius Luiz - 240421212
Pablo Vinicius - 19933212

https://github.com/arthvin/provaDesafio2

**Comment by gabriel-guerra** [comment]
Gabriel Sestito Guerra RA: 23025044-2
Lucas Niguti Dos Santos RA: 22019975-2
Renan Tonon de Oliveira RA: 22188153-2
Willian Hideaki Kakihata RA: 22015763-2

https://github.com/gabriel-guerra/desafio-profissional-p2

**Comment by RicardooFilho** [comment]
Ricardo Francisco da Silva Filho - RA: 22019957-2
Lorenzo Marzola Begnozzi - RA: 23067179-2
João Pedro Hieda Bortolotto - RA: 22231114-2
Vinicius Monteiro de Araujo Vilela - RA: 22276395-2

https://github.com/ViniciusMVilela/api-DandD

Collection do Postman: 
[Prova Desafio Profissional 2º BIM.postman_collection.json](https://github.com/user-attachments/files/15949028/Prova.Desafio.Profissional.2.BIM.postman_collection.json)

**Comment by willyantomaz** [comment]
willyan santos tomaz e silva R.A 22014128-2
Gabriel Alexandre Marassi Sitta R.A 22302091-2
ANDRE LUIS JACOB ROMAN R.A 22014551-2

https://github.com/willyantomaz/D-D

**Comment by Berkhz** [comment]
Kauan Henrique Bertalha 222620742
Efigênio Guerra Neto 222282892
Matheus Toscano Rossini 222122622
João Paulo Andrade 220126462

https://github.com/Berkhz/rpg

[response.json](https://github.com/user-attachments/files/15949299/response.json)

**Comment by mateusfb1103** [comment]
Mateus Felipe Brunetti dos Santos, RA: 22012698-2
Vitor Galetti Martins, RA: 22019959-2
Daniel Borrionuevo Gomes, RA: 220144962

https://github.com/mateusfb1103/prova-DP2bim
