### ISSUE TITLE
Consumindo APIs e trabalhando assincronia

### ISSUE THREAD

**Issue by ThiagoBussola** [TI-UNICESUMAR/2024-desafio-profissional-v-ESOFT5S-A#8]
Para exercitar o que estamos aprendendo em sala de aula, é proposta a seguinte atividade:
Contextualização: Vamos desenvolver uma aplicação que busque na poke API por151 pokemons. Será necessário mapear os dados, para cada pokemon os dados que serão relevantes para a aplicação são:
Nome, Tipo, Peso, Altura, Número da Dex e a o link da Sprite (imagem do pokemon).
O Número da dex deve ser correspondente a versão Fire Red do jogo, você pode entender como buscar esse dado facilmente pela documentação: https://pokeapi.co/

Após conseguir buscar os dados dos 151 pokemons, será necessário salvar eles em um arquivo .json

Passos:

1 - Buscar 151 pokemons
2 - Percorrer o resultado da busca anterior dando fetch em cada url (Ao realizar a busca de 151 pokemons ele retorna uma url para cada um e nessa url estão as informações que precisamos, diferente da ultima aula que procuramos apenas 1 pokemon)
3 - Mapear os dados para que sejam salvos somente as informações necessárias pedidas na contextualização
4 - Salvar no arquivo pokemon.json os 151 pokemons

URL para o primeiro fetch: https://pokeapi.co/api/v2/pokemon?limit=151

**Importante**: tente realizar todo o exercicios utilizando promises e promise.all, isso irá executar as promessas de forma concorrente e teremos uma melhor performance na busca e inserção de dados. 

Para finalizar, você deve criar esses mesmo script, porém agora utilizando o async await para cada fetch nos 151 pokemons. Isso deve ser feito para um fim didático, onde você poderá perceber a demora na execução da sua aplicação devido ao mal uso das promessas em forma sequencial.

Desafio extra: utilize seu JSON de pokemons para renderizar os 151 pokemons em uma página html ou em um pdf

**Comment by ashura-senpai** [comment]
https://github.com/ashura-senpai/atividadepokemon

Segue acima o meu repositório da atividade de presença do dia 28/02.

**Comment by rvbs1337** [comment]
https://github.com/rvbs1337/atividade-pokemon 
repositório com a atividade do dia 28-02

**Comment by amamaxs2** [comment]
https://github.com/amamaxs2/pokeapi-fire-red

Repositório da atividade do dia 28/02.

**Comment by EmersonTanno** [comment]
[https://github.com/EmersonTanno/dp_pokemon_promise.git](url)
Repositório com a atividade. 28/02

**Comment by cassiab13** [comment]
https://github.com/cassiab13/desafio

**Comment by AlineMisugui** [comment]
https://github.com/AlineMisugui/bussola
repositório com a atividade do dia 28-02

**Comment by Velinu** [comment]
https://github.com/Velinu/exPokemon

RA: 22012684-2

**Comment by kaikdorvalo** [comment]
https://github.com/kaikdorvalo/desafio_profissional_pokemons

Repositório com a atividade do dia 28-02

RA: 220939192

**Comment by rhayssaandretto** [comment]
[Repositório atividade do dia 28-02](https://github.com/rhayssaandretto/desafio-profissional-5sem)

**Comment by jeanunicesumar** [comment]
https://github.com/jeanunicesumar/2024-desafio-profissional-v-ESOFT5S-A/blob/main/151-pokemon/index.js
